import '@radix-ui/themes/styles.css';

// import { Inter } from "next/font/google";
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { Card, Container, Theme, ThemePanel } from '@radix-ui/themes';
import Navbar from './Navbar';
import AsideBar from './AsideBar';
import { cn } from '../lib/utils';
import AuthProvider from './auth/Provider';

// const inter = Inter({ subsets: ["latin"] });
export const fontSans = FontSans({
  subsets: ['latin'],
  // variable: "--font-sans",
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={inter.className}
        className={cn(
          'min-h-screen bg-background font-sans antialiased bg-gradient-to-r from-purple-50 via-purple-100 to-purple-50',
          fontSans.variable
        )}
      >
        {/*<NextThemeProvider> */}

        <AuthProvider>
          <Theme
            appearance="light"
            panelBackground="translucent"
            accentColor="purple"
          >
            <Container className="mx-auto w-9/12">
              <Card
                mb="3"
                mt="3"
                className="p-2"
                variant="classic"
                style={{ backgroundColor: 'var(--background-color)' }}
              >
                {/* <nav className=""> */}
                <Navbar />
                {/* </nav> */}
              </Card>
              <div className="grid grid-flow-row grid-cols-12 gap-2 ">
                <aside className="hidden lg:block text-sm lg:col-span-3  ">
                  <AsideBar />
                </aside>
                <main className="col-span-12 text-sm lg:col-span-9 min-h-screen ">
                  <Card
                    className="min-h-full"
                    style={{ backgroundColor: 'var(--background-color)' }}
                  >
                    {children}
                  </Card>
                </main>
              </div>
            </Container>

            {/* <ThemePanel /> */}
          </Theme>
        </AuthProvider>

        {/* </NextThemeProvider> */}
      </body>
    </html>
  );
}
